
package org.fbi.endpoint.tcs.org.tempuri.dhwebservice1.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/DHWebService1/Service")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param tellerId
     * @param txAmount
     * @param subCenterId
     * @param acctBal
     * @param outComName
     * @param avBal
     * @param operatorUserId
     * @param version
     * @param nodeId
     * @param txDate2
     * @param cTxAmount
     * @param txCode
     * @param outAcctId
     * @param outAcctName
     * @param userId
     * @param dcFlag
     * @param recCount
     * @param txSeqId
     * @param inBranchName
     * @param outComAcctId
     * @param acctId
     * @param outBranchName
     * @param bankIndex
     * @param curCode
     * @param funcCode
     * @param txDate1
     * @param reserve2
     * @param reserve1
     * @param abstractStr
     * @param cAcctBal
     * @param ccbsTellerId
     * @param voucherType
     * @param coSeqId
     * @param inAcctName
     * @param txTime1
     * @param txTime2
     * @param acctHostSeqId
     * @param _abstract
     * @param inAcctId
     * @param bankNodeId
     * @param channel
     * @param voucherId
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://tempuri.org/DHWebService1/Service/dianhui")
    @WebResult(name = "dianhuiResult", targetNamespace = "http://tempuri.org/DHWebService1/Service")
    @RequestWrapper(localName = "dianhui", targetNamespace = "http://tempuri.org/DHWebService1/Service", className = "org.tempuri.dhwebservice1.service.Dianhui")
    @ResponseWrapper(localName = "dianhuiResponse", targetNamespace = "http://tempuri.org/DHWebService1/Service", className = "org.tempuri.dhwebservice1.service.DianhuiResponse")
    public boolean dianhui(
            @WebParam(name = "Version", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String version,
            @WebParam(name = "TxCode", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txCode,
            @WebParam(name = "FuncCode", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String funcCode,
            @WebParam(name = "Channel", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String channel,
            @WebParam(name = "SubCenterId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String subCenterId,
            @WebParam(name = "NodeId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String nodeId,
            @WebParam(name = "TellerId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String tellerId,
            @WebParam(name = "TxSeqId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txSeqId,
            @WebParam(name = "TxDate1", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txDate1,
            @WebParam(name = "TxTime1", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txTime1,
            @WebParam(name = "UserId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String userId,
            @WebParam(name = "OperatorUserId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String operatorUserId,
            @WebParam(name = "RecCount", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String recCount,
            @WebParam(name = "AcctId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String acctId,
            @WebParam(name = "AcctHostSeqId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String acctHostSeqId,
            @WebParam(name = "TxDate2", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txDate2,
            @WebParam(name = "OutAcctId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String outAcctId,
            @WebParam(name = "OutAcctName", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String outAcctName,
            @WebParam(name = "OutBranchName", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String outBranchName,
            @WebParam(name = "InAcctId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String inAcctId,
            @WebParam(name = "InAcctName", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String inAcctName,
            @WebParam(name = "InBranchName", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String inBranchName,
            @WebParam(name = "TxAmount", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txAmount,
            @WebParam(name = "AcctBal", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String acctBal,
            @WebParam(name = "AvBal", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String avBal,
            @WebParam(name = "CAcctBal", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String cAcctBal,
            @WebParam(name = "CTxAmount", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String cTxAmount,
            @WebParam(name = "CurCode", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String curCode,
            @WebParam(name = "DCFlag", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String dcFlag,
            @WebParam(name = "AbstractStr", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String abstractStr,
            @WebParam(name = "TxTime2", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String txTime2,
            @WebParam(name = "VoucherId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String voucherId,
            @WebParam(name = "VoucherType", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String voucherType,
            @WebParam(name = "CoSeqId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String coSeqId,
            @WebParam(name = "Abstract", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String _abstract,
            @WebParam(name = "BankNodeId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String bankNodeId,
            @WebParam(name = "CCBSTellerId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String ccbsTellerId,
            @WebParam(name = "BankIndex", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String bankIndex,
            @WebParam(name = "OutComAcctId", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String outComAcctId,
            @WebParam(name = "OutComName", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String outComName,
            @WebParam(name = "Reserve1", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String reserve1,
            @WebParam(name = "Reserve2", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String reserve2);

    /**
     * 
     * @param recCOMPANYNAME
     * @param tradeDATE
     * @param payACCOUNTNAME
     * @param bankSERIAL
     * @param dcFLAG
     * @param toCOMPANYCODE
     * @param purpose
     * @param recACCOUNT
     * @param payACCOUNT
     * @param voucherFLAG
     * @param apAMOUNT
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://tempuri.org/DHWebService1/Service/zongfenzhanghu")
    @WebResult(name = "zongfenzhanghuResult", targetNamespace = "http://tempuri.org/DHWebService1/Service")
    @RequestWrapper(localName = "zongfenzhanghu", targetNamespace = "http://tempuri.org/DHWebService1/Service", className = "org.tempuri.dhwebservice1.service.Zongfenzhanghu")
    @ResponseWrapper(localName = "zongfenzhanghuResponse", targetNamespace = "http://tempuri.org/DHWebService1/Service", className = "org.tempuri.dhwebservice1.service.ZongfenzhanghuResponse")
    public boolean zongfenzhanghu(
            @WebParam(name = "BANK_SERIAL", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String bankSERIAL,
            @WebParam(name = "TRADE_DATE", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String tradeDATE,
            @WebParam(name = "PAY_ACCOUNT", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String payACCOUNT,
            @WebParam(name = "PAY_ACCOUNT_NAME", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String payACCOUNTNAME,
            @WebParam(name = "AP_AMOUNT", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String apAMOUNT,
            @WebParam(name = "TO_COMPANY_CODE", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String toCOMPANYCODE,
            @WebParam(name = "REC_COMPANY_NAME", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String recCOMPANYNAME,
            @WebParam(name = "REC_ACCOUNT", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String recACCOUNT,
            @WebParam(name = "VOUCHER_FLAG", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String voucherFLAG,
            @WebParam(name = "PURPOSE", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String purpose,
            @WebParam(name = "DC_FLAG", targetNamespace = "http://tempuri.org/DHWebService1/Service")
            String dcFLAG);

}
