package org.fbi.endpoint.eai.transCreditInfoFromSBStoJDE;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-11T19:08:35.463+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "TransCreditInfoFromSBStoJDE", 
                  wsdlLocation = "file:/D:/fcdep/profile/TransCreditInfoFromSBStoJDE.wsdl",
                  targetNamespace = "http://www.example.org/TransCreditInfoFromSBStoJDE/") 
public class TransCreditInfoFromSBStoJDE_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/TransCreditInfoFromSBStoJDE/", "TransCreditInfoFromSBStoJDE");
    public final static QName TransCreditInfoFromSBStoJDESOAP = new QName("http://www.example.org/TransCreditInfoFromSBStoJDE/", "TransCreditInfoFromSBStoJDESOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/fcdep/profile/TransCreditInfoFromSBStoJDE.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransCreditInfoFromSBStoJDE_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/fcdep/profile/TransCreditInfoFromSBStoJDE.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransCreditInfoFromSBStoJDE_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransCreditInfoFromSBStoJDE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransCreditInfoFromSBStoJDE_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns TransCreditInfoFromSBStoJDE
     */
    @WebEndpoint(name = "TransCreditInfoFromSBStoJDESOAP")
    public TransCreditInfoFromSBStoJDE getTransCreditInfoFromSBStoJDESOAP() {
        return super.getPort(TransCreditInfoFromSBStoJDESOAP, TransCreditInfoFromSBStoJDE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransCreditInfoFromSBStoJDE
     */
    @WebEndpoint(name = "TransCreditInfoFromSBStoJDESOAP")
    public TransCreditInfoFromSBStoJDE getTransCreditInfoFromSBStoJDESOAP(WebServiceFeature... features) {
        return super.getPort(TransCreditInfoFromSBStoJDESOAP, TransCreditInfoFromSBStoJDE.class, features);
    }

}
