package org.fbi.endpoint.eai.transCreditInfoFromSBStoJDE;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-11T19:08:35.412+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://www.example.org/TransCreditInfoFromSBStoJDE/", name = "TransCreditInfoFromSBStoJDE")
@XmlSeeAlso({ObjectFactory.class})
public interface TransCreditInfoFromSBStoJDE {

    @WebResult(name = "FLAG", targetNamespace = "")
    @RequestWrapper(localName = "TransCreditInfoFromSBStoJDE", targetNamespace = "http://www.example.org/TransCreditInfoFromSBStoJDE/", className = "org.fbi.endpoint.eai.transCreditInfoFromSBStoJDE.TransCreditInfoFromSBStoJDE_Type")
    @WebMethod(operationName = "TransCreditInfoFromSBStoJDE", action = "http://www.example.org/TransCreditInfoFromSBStoJDE/TransCreditInfoFromSBStoJDE")
    @ResponseWrapper(localName = "TransCreditInfoFromSBStoJDEResponse", targetNamespace = "http://www.example.org/TransCreditInfoFromSBStoJDE/", className = "org.fbi.endpoint.eai.transCreditInfoFromSBStoJDE.TransCreditInfoFromSBStoJDEResponse")
    public java.lang.String transCreditInfoFromSBStoJDE(
        @WebParam(name = "in", targetNamespace = "")
        org.fbi.endpoint.eai.transCreditInfoFromSBStoJDE.InType in
    );
}
