//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.10 at 09:34:41 PM CST 
//


package org.fbi.endpoint.mbp.domain.transactrequest;

import org.fbi.endpoint.mbp.domain.ClientRequestRoot;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Head"/>
 *         &lt;element ref="{}Param"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "head",
    "param"
})
@XmlRootElement(name = "root")
public class TransactRequestRoot extends ClientRequestRoot {

    @XmlElement(name = "Param", required = true)
    protected TransactRequestParam param;

    /**
     * Gets the value of the param property.
     *
     * @return
     *     possible object is
     *     {@link TransactRequestParam }
     *
     */
    public TransactRequestParam getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     *
     * @param value
     *     allowed object is
     *     {@link TransactRequestParam }
     *     
     */
    public void setParam(TransactRequestParam value) {
        this.param = value;
    }

    @Override
    public String toString() {
        return "Root{" +
                "head=" + head +
                ", param=" + param +
                '}';
    }
}
